services:
  db:
    image: postgres:alpine3.23
    container_name: chinwag-postgres    
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data   
    networks:
      - chinwag_net   # join the network


volumes:
  pgdata:
   
networks:
  chinwag_net:
    name: chinwag_net

