services:
  db:
    image: postgres:alpine3.23
    container_name: chinwag-postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chinwag_net

  db_test:
    image: postgres:alpine3.23
    container_name: chinwag-postgres-test
    env_file:
      - ./.env.test
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE_TEST}
    ports:
      - "${PGPORT_TEST}:${PGPORT_TEST}"   # test DB runs on a different port
    volumes:
      - /var/lib/postgresql/data
    networks:
      - chinwag_net

volumes:
  pgdata:
  pgdata_test:

networks:
  chinwag_net:
    name: chinwag_net